### ISSUE TITLE
Submodels: <*-offset> is deprecated. Use <offsets> instead

### ISSUE THREAD

**Issue by onox** [wlbragg/J3Cub#1]
Starting the J3Cub prints `Submodels: <*-offset> is deprecated. Use <offsets> instead` in the console.

The file `Models/retardant_drop-submodel.xml` is using:

```xml
<x-offset>  0.0 </x-offset>
<y-offset>  0.0  </y-offset>
<z-offset> -1.0 </z-offset>
<yaw-offset>0</yaw-offset>
<pitch-offset>-90</pitch-offset>
```

You should be able to replace this with:

```xml
<offsets>
    <x-m>-0.0</x-m>
    <y-m> 0.0</y-m>
    <z-m>-0.3048</z-m>
    <heading-deg>
        <value>0.0</value>
    </heading-deg>
    <pitch-deg>
        <value>-90.0</value>
    </pitch-deg>
</offsets>
```

Everything is in meters now. X-axis is reversed (with respect to `<x-offset>`). Values can be dynamic: you can use `<property>`, `<expression>`, `<value>`, `<scale>`, `<offset>`, `<min>`, `<max>`, `<abs>`, and `<period>`.

See http://wiki.flightgear.org/Howto:Add_submodels#Step_2:_Define_the_position_and_orientation

I added this in FG 3.6 (unreleased), so you need FG 2016.0 or higher.

**Comment by wlbragg** [comment]
Thanks @onox!
