### ISSUE TITLE
Fatal on launch

### ISSUE THREAD

**Issue by Octal450** [wlbragg/J3Cub#2]
In File J3Cub/J3Cub.xml line 1896
j3cub-persistent.xml is not there in my systems folder.

had to comment this out to launch.

**Comment by wlbragg** [comment]
@it0uchpods where did you get the aircraft files from?
This version here (master) shows that system file include line is at 1934 and the file is there in /Systems/j3cub-persistent.xml
and in fgaddon the same thing. So maybe your not up-to-date?

However, after looking at fgaddon to compare and make sure it was the same as this version I noticed @lbrenta has made some bug fixes to the fgaddon files that are not included here, so I need to review those changes and incorporate them here to sinc these repos. But I don't see where that would have caused the issue your raising.

**Comment by Octal450** [comment]
I just did a fresh clone from this repo.


The file is missing from Systems, so maybe you didn't update this from FGAddon? If you could sync that, I would appreciate it, as git is easier for me :)

Thanks
Josh

**Comment by wlbragg** [comment]
Your right Josh, sorry for the confusion. I'm trying to get it updated but am having issues with the svn side of things.
As soon as I sort it out I will update this.

**Comment by wlbragg** [comment]
@it0uchpods OK, should be ready to go and synced with FGADDON.

**Comment by Octal450** [comment]
Fixed. Thank you. 😃
